# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-10 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='type',
            field=models.IntegerField(choices=[('A', 1), ('B', 2)], null=True),
        ),
    ]
