# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-10 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0012_auto_20161027_1250'),
        ('certificates', '0002_certificates_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Building.ObjectCompany'),
        ),
    ]
