# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-10 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_certificates_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='type',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], null=True),
        ),
    ]
