# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='genPlan',
            field=models.ImageField(upload_to=''),
        ),
    ]
