# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0002_auto_20161001_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='object',
            options={'verbose_name': '\u041e\u0431\u044a\u0435\u043a\u0442\u044b', 'verbose_name_plural': '\u041e\u0431\u044a\u0435\u043a\u0442\u044b'},
        ),
    ]
