# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0003_auto_20161003_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Companies',
                'verbose_name': '\u041a\u043e\u043c\u043f\u0430\u043d\u0438\u044f',
                'verbose_name_plural': '\u041a\u043e\u043c\u043f\u0430\u043d\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='ObjectEntrance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='entrance')),
            ],
            options={
                'db_table': 'ObjectEntrance',
                'verbose_name': '\u041f\u043e\u0434\u044a\u0435\u0437\u0434',
                'verbose_name_plural': '\u041f\u043e\u0434\u044a\u0435\u0437\u0434\u044b',
            },
        ),
        migrations.CreateModel(
            name='ObjectFlats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ObjectFlats',
                'verbose_name': '\u041f\u043b\u0430\u043d\u0438\u0440\u043e\u0432\u043a\u0430 \u043a\u0432\u0430\u0440\u0442\u0438\u0440',
                'verbose_name_plural': '\u041f\u043b\u0430\u043d\u0438\u0440\u043e\u0432\u043a\u0438 \u043a\u0432\u0430\u0440\u0442\u0438\u0440',
            },
        ),
        migrations.CreateModel(
            name='ObjectGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='gallery')),
            ],
            options={
                'db_table': 'ObjectsGallery',
                'verbose_name': '\u0413\u0430\u043b\u043b\u0435\u0440\u0435\u044f',
                'verbose_name_plural': '\u0413\u0430\u043b\u043b\u0435\u0440\u0435\u0438',
            },
        ),
        migrations.AlterModelOptions(
            name='object',
            options={'verbose_name': '\u041e\u0431\u044a\u0435\u043a\u0442', 'verbose_name_plural': '\u041e\u0431\u044a\u0435\u043a\u0442\u044b'},
        ),
        migrations.AddField(
            model_name='object',
            name='built',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='object',
            name='entrance',
            field=models.ImageField(blank=True, null=True, upload_to='objects/entrance'),
        ),
        migrations.AlterField(
            model_name='object',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='genPlan',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='object',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Building.ObjectCompany'),
        ),
        migrations.AddField(
            model_name='object',
            name='gallery',
            field=models.ManyToManyField(blank=True, null=True, to='Building.ObjectGallery'),
        ),
    ]
