# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0004_auto_20161018_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='gallery',
        ),
        migrations.AddField(
            model_name='object',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Building.ObjectGallery'),
        ),
    ]
