# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0005_auto_20161018_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='livingComplex',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
