# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0006_object_livingcomplex'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectflats',
            name='render',
            field=models.ImageField(null=True, upload_to='flats/'),
        ),
        migrations.AlterField(
            model_name='object',
            name='livingComplex',
            field=models.CharField(choices=[('A', '\u0416\u041a "\u0423\u043b\u0430\u043d-2"'), ('B', '\u0416\u041a "\u0421\u043e\u043b\u043d\u0435\u0447\u043d\u044b\u0439"')], max_length=255, null=True),
        ),
    ]
