# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0008_object_flats'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectflats',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objectflats',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
