# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0010_auto_20161020_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='entrance',
        ),
        migrations.AddField(
            model_name='object',
            name='entrance1',
            field=models.ImageField(null=True, upload_to='entrance'),
        ),
        migrations.AddField(
            model_name='object',
            name='entrance2',
            field=models.ImageField(null=True, upload_to='entrance'),
        ),
    ]
