# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0011_auto_20161020_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='genPlan',
            field=models.ImageField(blank=True, null=True, upload_to='gen-plan'),
        ),
    ]
