# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.ImageField(upload_to='technic')),
                ('title', models.CharField(max_length=255)),
                ('exploitation', models.CharField(max_length=255)),
                ('ladleVolume', models.CharField(max_length=255)),
                ('depthDigging', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Technic',
            },
        ),
        migrations.CreateModel(
            name='TechnicCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.ImageField(upload_to='technic/category')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
    ]
