# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Technic', '0002_technic_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='technic',
            name='subCategoey',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
