# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Technic', '0003_technic_subcategoey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technic',
            old_name='subCategoey',
            new_name='subCategory',
        ),
    ]
