# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Technic', '0004_auto_20161002_1003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technic',
            options={'verbose_name': '\u0422\u0435\u0445\u043d\u0438\u043a\u0430', 'verbose_name_plural': '\u0422\u0435\u0445\u043d\u0438\u043a\u0430'},
        ),
        migrations.AlterModelOptions(
            name='techniccategory',
            options={'verbose_name': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f \u0442\u0435\u0445\u043d\u0438\u043a\u0438', 'verbose_name_plural': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f \u0442\u0435\u0445\u043d\u0438\u043a\u0438'},
        ),
        migrations.AddField(
            model_name='technic',
            name='amplitude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0410\u043c\u043f\u043b\u0438\u0442\u0443\u0434\u0430'),
        ),
        migrations.AddField(
            model_name='technic',
            name='capacity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0413\u0440\u0443\u0437\u043e\u043f\u043e\u0434\u044a\u0435\u043c\u043d\u043e\u0441\u0442\u044c'),
        ),
        migrations.AddField(
            model_name='technic',
            name='engineVolume',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041e\u0431\u044a\u0451\u043c \u0434\u0432\u0438\u0433\u0430\u0442\u0435\u043b\u044f'),
        ),
        migrations.AddField(
            model_name='technic',
            name='fuelBank',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0422\u043e\u043f\u043b\u0438\u0432\u043d\u044b\u0439 \u0431\u0430\u043a'),
        ),
        migrations.AddField(
            model_name='technic',
            name='fullMass',
            field=models.CharField(max_length=255, null=True, verbose_name='\u041f\u043e\u043b\u043d\u0430\u044f \u043c\u0430\u0441\u0441\u0430'),
        ),
        migrations.AddField(
            model_name='technic',
            name='maxSpeed',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041c\u0430\u043a\u0441. \u0421\u043a\u043e\u0440\u043e\u0441\u0442\u044c'),
        ),
        migrations.AddField(
            model_name='technic',
            name='power',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041c\u043e\u0449\u043d\u043e\u0441\u0442\u044c'),
        ),
        migrations.AlterField(
            model_name='technic',
            name='depthDigging',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0413\u043b\u0443\u0431\u0438\u043d\u0430 \u043a\u043e\u043f\u0430\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='technic',
            name='exploitation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u042d\u043a\u0441\u043f\u043b\u0443\u0430\u0442\u0430\u0446\u0438\u043e\u043d\u043d\u0430\u044f \u043c\u0430\u0441\u0441\u0430'),
        ),
        migrations.AlterField(
            model_name='technic',
            name='ladleVolume',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041e\u0431\u044a\u0451\u043c \u043a\u043e\u0432\u0448\u0430'),
        ),
        migrations.AlterField(
            model_name='technic',
            name='preview',
            field=models.ImageField(upload_to='technic', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='technic',
            name='subCategory',
            field=models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='technic',
            name='title',
            field=models.CharField(max_length=255, verbose_name='\u041c\u043e\u0434\u0435\u043b\u044c'),
        ),
    ]
