# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Technic', '0007_technic_tankvolume'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='technic',
            table='technic',
        ),
    ]
