# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Technic', '0008_auto_20161020_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technic',
            name='preview',
            field=models.ImageField(upload_to='', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
