# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Technic', '0009_auto_20161021_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='technic',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0426\u0435\u043d\u0430'),
        ),
    ]
