# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Technic', '0010_technic_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='technic',
            name='price_fuel',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0426\u0435\u043d\u0430 \u0441 \u0443\u0447\u0451\u0442\u043e\u043c \u0442\u043e\u043f\u043b\u0438\u0432\u0430'),
        ),
        migrations.AlterField(
            model_name='technic',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0426\u0435\u043d\u0430 \u0431\u0435\u0437 \u0443\u0447\u0451\u0442\u0430 \u0442\u043e\u043f\u043b\u0438\u0432\u0430'),
        ),
    ]
